version: "3.3"
services:
  dhbw_lb_balancer:
    container_name: dhbw_lb_balancer
    build:
      context: ./balancer
      dockerfile: Dockerfile
    image: dhbw_lb_balancer
    ports:
      - "34205:80"
    environment:
      - NODE_ENV=production
      - CONFIG_FILE=/config-deploy.example.yml
    networks:
      - sebamomann_dhbw_loadbalancer
  dhbw_lb_client:
    container_name: dhbw_lb_client
    build:
      context: ./client
      dockerfile: Dockerfile-Deploy
      args:
        prod: "true"
    ports:
      - "34204:80"
    image: dhbw_lb_client
    networks:
      - sebamomann_dhbw_loadbalancer
  dhbw_lb_service1:
    container_name: dhbw_lb_service1
    build: ./service
    image: dhbw_lb_service1
    ports:
      - "34206:8080"
    environment:
      - NAME=server1
      - BALANCER_URL=dhbw_lb_balancer
    networks:
      - sebamomann_dhbw_loadbalancer
  dhbw_lb_service2:
    container_name: dhbw_lb_service2
    build: ./service
    image: dhbw_lb_service2
    ports:
      - "34207:8080"
    environment:
      - NAME=server2
      - BALANCER_URL=dhbw_lb_balancer
    networks:
      - sebamomann_dhbw_loadbalancer
  dhbw_lb_service3:
    container_name: dhbw_lb_service3
    build: ./service
    image: dhbw_lb_service3
    ports:
      - "34208:8080"
    environment:
      - NAME=server3
      - BALANCER_URL=dhbw_lb_balancer
    networks:
      - sebamomann_dhbw_loadbalancer
networks:
  sebamomann_dhbw_loadbalancer:
    external:
      name: sebamomann_dhbw_loadbalancer
