port: 80
#strategy: round-robin
#strategy: least-connection
#strategy: ip-hash
strategy: resource-based
servers:
  - host: server1
    name: server1
    port: 8080
  - host: server2
    name: server2
    port: 8080
  - host: server3
    name: server3
    port: 8080
