FROM node:14

# Create app directory
WORKDIR /usr/src/app
COPY config-deploy.example.yml config.example.yml

# Install app dependenciesebamomann_dhbw_loadbalancer_main_dhbw_lb_service3
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY src src

EXPOSE 80
CMD [ "node", "src/index.js" ]
